[EasyLock] Add schema configuration
eonx-com/easy-monorepo pull request #1014
Opened 2022-07-29 20:26 UTC by alexndlm

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

This PR adds the `lock_keys` table to schema configuration.
In this case, Doctrine automatically generates migration and tracks this table.

2022-08-10 20:49 UTC, akl-95 requested changes

2022-08-10 20:49 UTC, akl-95 commented on packages/EasyLock/src/Bridge/Symfony/SchemaListener/EasyLockDoctrineSchemaSubscriber.php
> +namespace EonX\EasyLock\Bridge\Symfony\SchemaListener;
Please update `SchemaListener` -> `Subscribers`.

2022-08-11 06:18 UTC, alexndlm commented on packages/EasyLock/src/Bridge/Symfony/SchemaListener/EasyLockDoctrineSchemaSubscriber.php
> +namespace EonX\EasyLock\Bridge\Symfony\SchemaListener;
Done

2022-08-11 07:24 UTC, akl-95 approved these changes

2022-08-16 09:40 UTC, itorgov submitted a review, later dismissed

2022-08-16 09:51 UTC, roman-eonx approved these changes

2022-08-18 07:48 UTC, roman-eonx approved these changes

2022-08-18 08:03 UTC, akl-95 approved these changes

2022-08-19 02:58 UTC, natepage approved these changes

2022-08-19 02:58 UTC, merged