[EasyCore] hotfix/open-api-normalizer
eonx-com/easy-monorepo pull request #1036
Opened 2022-09-09 06:31 UTC by alexandrtspl

* openApiNormalizer

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | #...

2022-09-12 09:42 UTC, alexndlm requested changes

2022-09-12 09:42 UTC, alexndlm commented on packages/EasyCore/src/Bridge/Symfony/ApiPlatform/OpenApi/Processor/DefaultDecorationProcessorInterface.php
> +interface DefaultDecorationProcessorInterface
I can't get why we need this interface?

2022-09-12 09:42 UTC, alexndlm commented on packages/EasyCore/src/Bridge/Symfony/ApiPlatform/OpenApi/Processor/DefaultDecorationProcessorInterface.php
> +interface DefaultDecorationProcessorInterface
Got it

2022-09-12 09:42 UTC, alexndlm commented on packages/EasyCore/src/Bridge/Symfony/ApiPlatform/OpenApi/Processor/UpdateDocsComponentsSchemasProcessor.php
> +        $dateTimeExample = CarbonImmutable::now()->toIso8601String();
Let's use here some exact date to make generated docs the same.

And let's add tests:
- two API resources, with all cases that we transform in our transformers.
- assert that generated JSON is the same.

Maybe we should think about creating the new package `easy-api-platform`, and move all related stuff there.

2022-09-12 09:42 UTC, alexndlm commented on packages/EasyCore/src/Bridge/Symfony/ApiPlatform/OpenApi/Provider/OpenApiContextProvider.php
> +                    'allowMissingFields' => true,
Looks that this must be `false`?

2023-05-17 23:47 UTC, natepage approved these changes

2023-05-17 23:47 UTC, natepage commented
Add comment after approving review

2023-05-17 23:53 UTC, natepage approved these changes
PLACEHOLDER

2023-05-18 00:12 UTC, natepage approved these changes

2023-05-18 00:18 UTC, natepage approved these changes

2023-05-18 01:50 UTC, natepage approved these changes

2023-05-18 01:58 UTC, natepage approved these changes

2023-05-18 02:08 UTC, natepage approved these changes

2023-05-18 02:13 UTC, natepage approved these changes

2023-05-18 02:14 UTC, natepage approved these changes
Nice work! Code review complete.

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

2023-05-18 02:35 UTC, natepage approved these changes
Nice job! 😊 Code review passed.

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

2023-05-23 04:34 UTC, natepage approved these changes
Code review successful. Nice work!

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

2023-09-12 06:28 UTC, closed without merging