Update phpunit config to new format
eonx-com/easy-monorepo pull request #1063
Opened 2022-10-29 16:57 UTC by alexndlm

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

2022-11-03 15:43 UTC, akl-95 requested changes

2022-11-03 15:54 UTC, alexndlm commented on phpunit.xml
> +        <include>
Two points here:
- we don't have such folders
- `packages/*/src` cover `packages/*/packages/*/src`

2022-11-07 06:25 UTC, akl-95 approved these changes

2022-11-16 05:04 UTC, natepage approved these changes

2022-11-16 05:04 UTC, merged