[EasyDoctrine] Add IntegerNumberType
eonx-com/easy-monorepo pull request #1103
Opened 2023-04-27 09:21 UTC by alexndlm

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

2023-04-27 10:00 UTC, roman-eonx requested changes

2023-04-28 10:08 UTC, roman-eonx requested changes

2023-04-28 13:01 UTC, roman-eonx commented on packages/EasyUtils/src/Validator/Constraints/AbstractNumberComparisonValidator.php
> +namespace EonX\EasyUtils\Validator\Constraints;
OK, let's follow the Symfony way here. And please ignore `\EonX\EasyCore\Bridge\Symfony\Validator\Constraints\IntegerValidator`, our intention is to get rid of EasyCore soon.

2023-04-28 13:09 UTC, alexndlm commented on packages/EasyUtils/src/Serializer/IntegerNumberNormalizer.php
> +namespace EonX\EasyUtils\Serializer;
Done

2023-04-28 13:09 UTC, alexndlm commented on packages/EasyUtils/src/ValueObject/Number.php
> +namespace EonX\EasyUtils\ValueObject;
Done

2023-04-28 13:09 UTC, alexndlm commented on packages/EasyUtils/src/Validator/Constraints/AbstractNumberComparisonValidator.php
> +namespace EonX\EasyUtils\Validator\Constraints;
Done

2023-04-28 13:09 UTC, alexndlm commented on packages/EasyUtils/src/Types/IntegerNumberType.php
> +final class IntegerNumberType extends DoctrineBigIntType
Done

2023-04-28 15:07 UTC, roman-eonx approved these changes

2023-05-02 10:11 UTC, roman-eonx approved these changes

2023-05-02 15:21 UTC, akl-95 approved these changes

2023-05-03 02:30 UTC, natepage approved these changes

2023-05-03 03:06 UTC, merged