[EasyCore] Add JsonbType and Contains function support for PostgreSQL
eonx-com/easy-monorepo pull request #333
Opened 2020-08-28 11:14 UTC by ERuban

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes 
| BC breaks?    | yes     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | ...   

Add Jsonb type for Doctrine DBAL and CONTAINS function for ORM.

BC related to changed namespace for DBAL Types.

2020-08-28 11:20 UTC, roman-eonx submitted a review, later dismissed

2020-08-28 11:30 UTC, egor-dev approved these changes

2020-08-28 11:39 UTC, roman-eonx approved these changes

2020-08-28 14:18 UTC, BOB41K1987 requested changes

2020-08-28 14:28 UTC, ERuban commented on packages/EasyCore/tests/Doctrine/ORM/Query/AST/Functions/ContainsTest.php
> +        $this->mock(Node::class, static function (MockInterface $mock) use ($sqlWalker, $parameter): void {
done

2020-08-28 14:28 UTC, ERuban commented on packages/EasyCore/tests/Doctrine/DBAL/Types/JsonbTypeTest.php
> +        $value = \urldecode('some bad utf string %C4');
done

2020-08-28 14:29 UTC, ERuban commented on packages/EasyCore/tests/Doctrine/DBAL/Types/JsonbTypeTest.php
> +    public function testConvertToDatabaseValueSucceeds($phpValue, ?string $postgresValue): void
done

2020-08-28 14:29 UTC, BOB41K1987 approved these changes

2020-08-28 14:50 UTC, roman-eonx approved these changes

2020-08-28 15:43 UTC, egor-dev approved these changes

2020-08-31 12:45 UTC, natepage approved these changes

2020-08-31 12:45 UTC, merged