Feature/[EasyLogging] Implement LoggerAwareTrait
eonx-com/easy-monorepo pull request #413
Opened 2020-11-03 13:18 UTC by DKeeper

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |

2020-11-03 15:33 UTC, roman-eonx approved these changes

2020-11-04 13:49 UTC, egor-dev requested changes

2020-11-04 13:49 UTC, egor-dev commented on packages/EasyLogging/tests/AbstractTestCase.php
> +    protected function callPrivateMethod($object, string $method, ...$args)
Not used?

2020-11-04 13:49 UTC, egor-dev commented on packages/EasyLogging/tests/AbstractTestCase.php
> +    protected function setPrivatePropertyValue($object, string $property, $value): void
Not used?

2020-11-05 16:53 UTC, DKeeper commented on packages/EasyLogging/tests/AbstractTestCase.php
> +    protected function callPrivateMethod($object, string $method, ...$args)
Removed.

2020-11-05 16:53 UTC, DKeeper commented on packages/EasyLogging/tests/AbstractTestCase.php
> +    protected function setPrivatePropertyValue($object, string $property, $value): void
Removed.

2020-11-05 16:59 UTC, roman-eonx approved these changes

2020-11-06 13:09 UTC, egor-dev approved these changes

2020-11-09 01:12 UTC, natepage approved these changes

2020-11-09 01:13 UTC, merged