Relates to #429
eonx-com/easy-monorepo pull request #430
Opened 2020-12-04 03:51 UTC by jayaregalinadaflexisourceit

- Bind `ErrorHandlerInterface` and inject to `ExceptionHandler`
- Update documentation in Laravel/Lumen setup

Signed-off-by: Jay Are Galinada <jayare.galinada@flexisourceit.com.au>

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | #429 ...

2020-12-07 23:00 UTC, natepage requested changes

2020-12-07 23:00 UTC, natepage commented on packages/EasyErrorHandler/docs/laravel/lumen_install.md
> +### Change Exception Handler
That's not really true 😄 
We are already binding the package exception handler to the illuminate contract within `EasyErrorHandlerServiceProvider.php` so no need to do it here again.
What the documentation should say is to make sure the package works as expected they remove any binding of the exception handler contract.

2020-12-07 23:31 UTC, natepage commented
@jayaregalinadaflexisourceit Thank you for your PR, please try to make the title meaningful so people can understand what you're trying to achieve by reading it 😉

2020-12-09 02:45 UTC, jayaregalinadaflexisourceit commented
Close this and refer to #438

2020-12-09 02:45 UTC, closed without merging