[EasyApiToken] Updated Symfony configs.
eonx-com/easy-monorepo pull request #809
Opened 2021-12-02 10:50 UTC by itorgov

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 

[EasyBugsnag] Updated Symfony configs.
[EasyCore] Updated Symfony configs.
[EasyDoctrine] Type-hinting improvements.
[EasyEventDispatcher] Updated Symfony configs.
[EasyHttpClient] Updated Symfony configs.
[EasyLock] Updated Symfony configs.
[EasyLogging] Updated Symfony configs.
[EasySecurity] Updated Symfony configs and improved the `ContextAuthenticator` class.

2021-12-02 12:45 UTC, roman-eonx submitted a review, later dismissed

2021-12-02 13:40 UTC, roman-eonx approved these changes

2021-12-03 06:18 UTC, roman-eonx approved these changes

2021-12-03 14:34 UTC, roman-eonx approved these changes

2021-12-06 01:56 UTC, natepage requested changes
Please fix ecs issues.

Also, heads up, because the monorepo currently supports Symfony 4.4, we cannot use `service()` function like that yet, I'm currently trying to think about our best option here :smile:

2021-12-17 06:56 UTC, closed without merging