[EasyBatch] Symfony service configuration fix
eonx-com/easy-monorepo pull request #840
Opened 2022-01-27 13:14 UTC by voodooism

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes

2022-01-27 13:17 UTC, alexndlm submitted a review, later dismissed

2022-01-27 13:22 UTC, akl-95 approved these changes

2022-01-27 13:51 UTC, akl-95 requested changes
Pls fix actions.

2022-01-27 14:17 UTC, voodooism commented
Actions are fixed

2022-01-28 13:12 UTC, roman-eonx approved these changes

2022-02-02 13:02 UTC, akl-95 approved these changes

2022-02-03 14:52 UTC, natepage approved these changes

2022-02-03 14:52 UTC, merged