[EasyDoctrine] Use myclabs/deep-copy
eonx-com/easy-monorepo pull request #843
Opened 2022-01-28 15:26 UTC by alexndlm

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

2022-02-16 07:19 UTC, mvlad approved these changes

2022-02-17 14:52 UTC, akl-95 requested changes

2022-02-17 14:52 UTC, akl-95 commented on packages/EasyDoctrine/src/Dispatchers/DeferredEntityEventDispatcher.php
> +        $copier = new DeepCopy();
Let's inject it as a service.

2022-02-18 17:54 UTC, alexndlm commented on packages/EasyDoctrine/src/Dispatchers/DeferredEntityEventDispatcher.php
> +        $copier = new DeepCopy();
Have done.

2022-03-28 11:09 UTC, closed without merging